{% set version = "1.3.13" %}
{% set python = "python3" %}

package:
  name: salib
  version: {{ version }}
source:
  fn: SALib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/S/SALib/SALib-{{ version }}.tar.gz
  sha256: 509c149c81d9cbf7e54ab275769bd855fb0aa5a699570c76f2ffa183a9c4041a
build:
  number: 0
  noarch: python
  script: {{ python }} -m pip install . --no-deps -vv
requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=38.3
    - pyscaffold >=3.2.3
  run:
    - python >=3.6
    - numpy >=1.16
    - pandas >=1.0.3
    - scipy
    - matplotlib-base
test:
  source_files:
    # copy files from source dir into temp test dir necessary for tests to pass
    - tests/*
    - src/*
  imports:
    - SALib
  requires:
    - pytest
    - pytest-cov
  commands:
    - pytest
about:
  home: http://salib.github.io/SALib/
  license: MIT
  license_file: LICENSE.md
  summary: Sensitivity Analysis Library
extra:
  recipe-maintainers:
    - jschueller
    - willu47
    - ConnectedSystems
