{% set version = "1.4.6.1" %}

package:
  name: salib
  version: {{ version }}
source:
  fn: SALib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/salib/salib-{{ version }}.tar.gz
  sha256: 14337239f1e92960e8f53774c27b1d072253790b57edbbebd290057a5eeb3858
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
requirements:
  host:
    - pip
    - python >=3.8
    - hatchling >=1.8.1
  run:
    - python >=3.8
    - numpy >=1.20.3
    - pandas >=1.1.2
    - scipy >=1.7.3
    - matplotlib-base
    - pathos >=0.2.5
    - multiprocess
test:
  imports:
    - SALib
about:
  home: http://salib.github.io/SALib/
  dev_url: https://github.com/SALib/SALib
  doc_url: http://salib.readthedocs.org
  license: MIT
  license_file: LICENSE.md
  summary: Sensitivity Analysis Library
  description: |
    Python implementations of commonly used sensitivity analysis methods.
    Useful in systems modeling to calculate the effects of model inputs or
    exogenous factors on outputs of interest.

extra:
  recipe-maintainers:
    - jschueller
    - willu47
    - ConnectedSystems
