{% set version = "1.1.3" %}

package:
  name: salib
  version: {{ version }}

source:
  fn: salib-{{ version }}.tar.gz
  url: https://github.com/SALib/SALib/archive/v{{ version }}.tar.gz
  sha256: e6256c2dfcffb98bb975fcd6fd2330e1a5d2727da648b23f0938ad35d552206b

build:
  number: 0
  noarch: python
  script:
    - git init  # hack to build from tarball
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pyscaffold
  run:
    - python
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - SALib

about:
  home: http://salib.github.io/SALib/
  license: MIT
  license_file: LICENSE.md
  summary: Sensitivity Analysis Library


extra:
  recipe-maintainers:
    - jschueller
