{% set version = "1.1.2" %}

package:
  name: salib
  version: {{ version }}

source:
  fn: salib-{{ version }}.tar.gz
  url: https://github.com/SALib/SALib/archive/v{{ version }}.tar.gz
  sha256: 5ef6444d2323404faaf8ca1579314f1964da21533f9d32887a29db35e991a6f0

build:
  number: 1
  noarch: python
  script:
    - git init  # hack to build from tarball
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pip
    - pyscaffold
  run:
    - python
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - SALib

about:
  home: http://salib.github.io/SALib/
  license: MIT
  license_file: LICENSE.md
  summary: Sensitivity Analysis Library


extra:
  recipe-maintainers:
    - jschueller
    - willu47
