{% set version = "1.3.6" %}

package:
  name: salib
  version: {{ version }}

source:
  fn: salib-{{ version }}.tar.gz
  url: https://github.com/SALib/SALib/archive/v{{ version }}.tar.gz
  sha256: 8ba5dacbba4b44473dea8f5695c5594c18d9d5cd302e4cfcdaa90a17a12da7a1

build:
  number: 0
  noarch: python
  script:
    - git init  # hack to build from tarball
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pyscaffold
  run:
    - python
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - SALib

about:
  home: http://salib.github.io/SALib/
  license: MIT
  license_file: LICENSE.md
  summary: Sensitivity Analysis Library


extra:
  recipe-maintainers:
    - jschueller
